name: Build mimikatz

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Windows SDK 8.1
      run: |
        choco install windows-sdk-8.1 -y

    - name: Install v141 build tools
      run: |
        choco install visualstudio2017buildtools --version=15.9.45.0 -y
        choco install visualstudio2017-workload-vctools -y
        "& 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe' modify --installPath 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools' --add Microsoft.VisualStudio.Component.VC.v141.x86.x64 --quiet --wait --norestart"

    - name: Apply fixes for macro redefinition
      run: |
        echo "#ifndef PRINTER_NOTIFY_CATEGORY_ALL" >> modules/rpc/kull_m_rpc_ms-rprn.h
        echo "#define PRINTER_NOTIFY_CATEGORY_ALL 0x00FFFFFF" >> modules/rpc/kull_m_rpc_ms-rprn.h
        echo "#endif" >> modules/rpc/kull_m_rpc_ms-rprn.h

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build mimikatz
      run: |
        msbuild /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v141 mimikatz.sln

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mimikatz-build
        path: |
          x64/Release/
