name: Build mimikatz

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install v141_xp build tools
      run: |
        choco install visualstudio2017buildtools --version=15.9.45.0 -y
        choco install visualstudio2017-workload-vctools -y

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build mimikatz
      run: |
        msbuild /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v141 mimikatz.sln

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mimikatz-build
        path: |
          x64/Release/
